spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ga-db?serverTimezone=UTC
    username: root
    password: admin1234

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: True
    show-sql: True
